# Nixpacks configuration for VanEase Rental System

[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.install]
cmds = [
  "cd backend_web/VanEase",
  "chmod +x mvnw"
]

[phases.build]
cmds = [
  "cd backend_web/VanEase",
  "./mvnw clean package -DskipTests"
]

[start]
cmd = "cd backend_web/VanEase && java -Dspring.profiles.active=railway -jar target/VanEase-0.0.1-SNAPSHOT.jar"

[variables]
PROJECT_ROOT = "backend_web/VanEase"

