[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = [
  "cd backend_web/VanEase",
  "chmod +x mvnw",
  "./mvnw clean package -DskipTests"
]

[start]
cmd = "cd backend_web/VanEase && java -Dspring.profiles.active=railway -jar target/VanEase-0.0.1-SNAPSHOT.jar"
