[phases.setup]
nixPkgs = ["maven", "openjdk17"]

[phases.build]
cmds = [
  "cd backend_web/VanEase",
  "chmod +x mvnw",
  "mvn clean package -DskipTests"
]

[start]
cmd = "java -Dspring.profiles.active=prod -jar backend_web/VanEase/target/VanEase-0.0.1-SNAPSHOT.jar"
