[build]
builder = "nixpacks"
buildCommand = "cd backend_web/VanEase && chmod +x mvnw && ./mvnw package -DskipTests"

[deploy]
startCommand = "cd backend_web/VanEase && java -Dspring.profiles.active=prod -jar target/VanEase-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/health/simple"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
nixPackages = ["openjdk17", "maven"]

[phases.setup]
aptPkgs = ["default-jre", "default-jdk"]
