[build]
builder = "nixpacks"
buildCommand = "cd backend_web/VanEase && chmod +x mvnw && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -Xms128m -Xmx512m -Dspring.profiles.active=prod -jar backend_web/VanEase/target/VanEase-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/health/ping"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
nixPackages = ["openjdk21", "maven"]
